name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, curl, zip, bcmath, pdo, pdo_mysql
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'master-saas/package-lock.json'

    - name: Install Composer dependencies
      working-directory: ./master-saas
      run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

    - name: Install NPM dependencies
      working-directory: ./master-saas
      run: npm ci

    - name: Build frontend assets
      working-directory: ./master-saas
      run: npm run build

    - name: Create deployment package
      run: |
        cd master-saas
        tar -czf ../deploy-package.tar.gz \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='tests' \
          --exclude='.env.example' \
          public/build \
          resources/js/Pages \
          resources/js/Components \
          routes/web.php

    - name: Deploy to Hostinger via FTP
      env:
        FTP_SERVER: ${{ secrets.HOSTINGER_FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp

        # Upload deployment package
        lftp -c "
        set ftp:ssl-allow no;
        set net:timeout 10;
        set net:max-retries 3;
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
        cd /domains/master.astracareportal.com/private_html;
        put deploy-package.tar.gz;
        bye;
        "

        echo "✅ Deployment package uploaded successfully!"

    - name: Extract files via SSH (optional)
      continue-on-error: true
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTINGER_SSH_HOST }}
        username: ${{ secrets.HOSTINGER_SSH_USERNAME }}
        password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
        port: ${{ secrets.HOSTINGER_SSH_PORT }}
        script: |
          cd /home/u458200173/domains/master.astracareportal.com/private_html
          tar -xzf deploy-package.tar.gz
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          chmod -R 755 storage bootstrap/cache
          echo "✅ Deployed and optimized!"

    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Deployment to Hostinger successful!"
        echo "Site: https://master.astracareportal.com"
        echo "Health: https://master.astracareportal.com/health"
